<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChargeAmount</name>
   <tag></tag>
   <elementGuidId>f3b5e98a-1369-40fe-ac80-077aa67076fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coverChargeAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coverChargeAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f95fe588-daf8-4e81-ac6a-3d206f452c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter the amount</value>
      <webElementGuid>a151b24a-aa91-4ff6-a565-e00a9a0aceb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coverChargeAmount</value>
      <webElementGuid>1ee62874-8472-4d68-bb26-5bf5997f75ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>fb49a008-0e1f-40a9-81a8-78543912a8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d274935d-e555-476b-8888-da5ce48e78b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coverChargeAmount&quot;)</value>
      <webElementGuid>4439cc0b-9aba-4df3-8a8a-b14fbe383f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coverChargeAmount']</value>
      <webElementGuid>458da9ae-5b5e-4e89-bd55-38b83ec920b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[3]/div[2]/div[2]/form/div[10]/div[6]/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>82634f52-03d8-4070-af4a-f761053c39bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>8369197c-48ff-4545-a5b5-4525f687498e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter the amount' and @id = 'coverChargeAmount' and @type = 'text']</value>
      <webElementGuid>c7e79364-b93d-43da-939d-d534b0b48a0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
