<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Click or drag file to this area to uplo_866c19</name>
   <tag></tag>
   <elementGuidId>3b31e3ca-25b6-45a3-b61d-8289b11a6546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[3]/div[2]/div[2]/form/div/div[3]/div/div/div/div/span/div/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-upload-drag-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba6c5226-a097-4c7a-b3aa-2192b8e46949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-upload-drag-container</value>
      <webElementGuid>8dab9363-c7b3-48c1-948a-1b747d3f1d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click or drag file to this area to uploadPNG, JPG, JPEG. (Max 2MB) (Recommended 1080 x 1080)</value>
      <webElementGuid>14818c94-97ac-4cdc-91cd-914b4d250d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;ant-row organizer-dashboard_dashboard__zwPV_&quot;]/div[@class=&quot;ant-col ant-col-24 organizer-dashboard_rightside__9SYiZ&quot;]/div[@class=&quot;organizer-dashboard_mainSection__y7Jve&quot;]/div[2]/div[@class=&quot;list-event_wrapper__mMi0A&quot;]/form[@class=&quot;ant-form ant-form-vertical list-event_form__WCfad&quot;]/div[@class=&quot;list-event_section__Oxtsr&quot;]/div[@class=&quot;ant-form-item list-event_item__1IcQa&quot;]/div[@class=&quot;ant-row ant-form-item-row&quot;]/div[@class=&quot;ant-col ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/span[1]/div[@class=&quot;ant-upload ant-upload-drag list-event_dragger__OEv9D&quot;]/span[@class=&quot;ant-upload ant-upload-btn&quot;]/div[@class=&quot;ant-upload-drag-container&quot;]</value>
      <webElementGuid>bcf083c4-1e9f-45bc-8d23-d3fe53be02f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[3]/div[2]/div[2]/form/div/div[3]/div/div/div/div/span/div/span/div</value>
      <webElementGuid>8be62ee8-54ad-4c4b-a7e7-8dba35edbfaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is the first image attendees will see at the top of your listing.'])[1]/following::div[7]</value>
      <webElementGuid>6813c8de-cbf3-4938-b697-89bb37583efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Banner'])[1]/following::div[8]</value>
      <webElementGuid>000b5f7d-b614-422b-8462-4faa302b081d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Info'])[2]/preceding::div[2]</value>
      <webElementGuid>b2777e0e-9380-4669-ae7c-f6245a7d50ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/span/div</value>
      <webElementGuid>a566189e-349a-41c7-8650-4d3cabf78c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Click or drag file to this area to uploadPNG, JPG, JPEG. (Max 2MB) (Recommended 1080 x 1080)' or . = 'Click or drag file to this area to uploadPNG, JPG, JPEG. (Max 2MB) (Recommended 1080 x 1080)')]</value>
      <webElementGuid>8391f26b-e034-42b1-8d38-50d7f44b726f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
