<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>endTime</name>
   <tag></tag>
   <elementGuidId>eaa56917-8cb8-4f50-ab1b-8e6a9657ad00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>681b0f49-506a-41d2-b1c4-4c13feae1ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>f42e9d23-40dd-410b-a603-0c65ee93d494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endTime</value>
      <webElementGuid>c85e1633-c095-4d58-a48a-4f374e1a4278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>45b507b0-3061-48e6-9cea-8a4d954e8239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-search-input</value>
      <webElementGuid>7a44a494-4f3b-4872-b93b-d0812e36ae41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>8b5c3965-7e2d-42ae-a752-a3c6f00cba8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>2c45b990-7548-4170-a56a-66bffe468aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>endTime_list</value>
      <webElementGuid>69f24969-a5a1-4d41-bfe9-a2082243e057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>29e28295-4660-4526-86df-7ff6e5772090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>endTime_list</value>
      <webElementGuid>ffc222f5-7660-4f85-abe4-e3844adf7c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>endTime_list_0</value>
      <webElementGuid>b8619549-82b5-4c4e-9572-2f027004834a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>39cf9f5e-a077-4626-97c8-f309bf9fe9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cff594c5-51ba-4795-903b-f53311624978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endTime&quot;)</value>
      <webElementGuid>d022f321-2b3e-4e29-97d9-f26637efe831</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endTime']</value>
      <webElementGuid>b9f9747b-7d11-48b7-bb21-b93069aa8669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[3]/div[2]/div[2]/form/div[10]/div[4]/div[2]/div/div/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>81baf3b2-cb89-4070-b237-15783702dc3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>6fd12c28-1265-4f56-942b-e4602ca51a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'endTime']</value>
      <webElementGuid>74b88b44-f4ed-4dff-8c9a-965d742de6ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
