<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date_dateAndTime</name>
   <tag></tag>
   <elementGuidId>2675a20c-35af-4d61-9792-56ed95352e2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateAndTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateAndTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cebf19f8-2c19-44e0-a0c3-b5d5077fb757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateAndTime</value>
      <webElementGuid>a17affbc-1f9e-4c8b-b94a-489478cad586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select date</value>
      <webElementGuid>ff92d59b-268f-4299-8eb0-17c4b2a37248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>93d00793-b5ee-4ba8-a108-b46e04eb931f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4eeff03a-3b5c-46fd-bc0c-588347726f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateAndTime&quot;)</value>
      <webElementGuid>49f865a7-9378-41ea-bf8c-d7933d752959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateAndTime']</value>
      <webElementGuid>1704efbd-29f0-4f18-976d-19241e832887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[3]/div[2]/div[2]/form/div[10]/div[3]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>a5db47c5-a02a-43fb-9ca5-a163faac00d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>5971cb46-0afa-4c3c-bf14-56232b9da71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dateAndTime' and @placeholder = 'Select date']</value>
      <webElementGuid>ed8c9bed-e39d-4827-aa54-3f102775c92c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
