<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cover Charge Amount_coverChargeAmount</name>
   <tag></tag>
   <elementGuidId>1610aa7a-54e3-4872-89d3-4ff7e1195965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coverChargeAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coverChargeAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49519101-6a92-4cbb-b283-ee6038f6715d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter the amount</value>
      <webElementGuid>d8e6d595-153a-4376-846d-63f95794083a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coverChargeAmount</value>
      <webElementGuid>8dde3046-4523-409b-bb32-ed64c3997b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>c1db0b25-c2be-4edd-a547-cce0c6a74d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a5c5433-186f-4c2e-b903-986403e2c7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coverChargeAmount&quot;)</value>
      <webElementGuid>3ce73ef5-5df4-4991-aa52-d77d7e510f83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coverChargeAmount']</value>
      <webElementGuid>ecf53869-f4e6-48ec-b3c3-d3fb54576989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[3]/div[2]/div[2]/form/div[10]/div[5]/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>5a0dc2e7-77ad-47d8-8f1c-6d6379e0bd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>ffbf52d4-9018-4afa-a735-cfb2c2e37fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter the amount' and @id = 'coverChargeAmount' and @type = 'text']</value>
      <webElementGuid>25523345-1a87-4698-b947-5132275ac676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
