<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_</name>
   <tag></tag>
   <elementGuidId>1a783336-325e-47aa-a61a-fa456be314bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section.img-crop-control.img-crop-control-zoom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit image'])[1]/following::section[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>ec429098-aa4e-4c71-96ec-3f90a90e2b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-crop-control img-crop-control-zoom</value>
      <webElementGuid>c12f034f-1876-481d-8141-9e7ff7ce43ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>－＋</value>
      <webElementGuid>33ccd4ec-0837-435f-93f6-4dbde20ff32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ant-scrolling-effect&quot;]/div[7]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap img-crop-modal&quot;]/div[@class=&quot;ant-modal&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/section[@class=&quot;img-crop-control img-crop-control-zoom&quot;]</value>
      <webElementGuid>54f803ce-d82b-4120-b4ad-ebb43a74b5fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit image'])[1]/following::section[1]</value>
      <webElementGuid>22c125bd-0319-4aa3-a65a-2b01d66ff3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/following::section[1]</value>
      <webElementGuid>a702f268-f2b7-466b-b35e-fa1bf6e58fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section</value>
      <webElementGuid>1a211483-683d-4f1b-a9ef-ca0fa3f5417f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = '－＋' or . = '－＋')]</value>
      <webElementGuid>90ad2169-ceaa-4215-97d5-5c8d01122efe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
