<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_Sign in with GoogleSign in with Google_264819_1</name>
   <tag></tag>
   <elementGuidId>3de3e634-aa8c-4eb1-b457-aaa7251e820b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body.qJTHM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>9d3a73e7-adaf-4c4f-833f-9d651b181973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qJTHM</value>
      <webElementGuid>ff555efb-5965-4110-8ae4-d8bf797955e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in with GoogleSign in with Googlegis.provider.button.bootstrap('CiIKFitMSHZuU1J5b2dwQkRkdHNpZGI5TkESBHdhcm4aAmVuGtgBCkkxMDM4MDc0Nzc0MjYyLWltNDVjaXAzdDBkcWw3ZzlqbDlyODk5YXM1ODVnYTd2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tEh1odHRwczovL29yZ2FuaXplci5mb3JtaS5jby5pbhoLZm9ybWkuY28uaW4qImh0dHBzOi8vZm9ybWkuY28uaW4vcHJpdmFjeS1wb2xpY3kyKGh0dHBzOi8vZm9ybWkuY28uaW4vdGVybXMtYW5kLWNvbmRpdGlvbnM6EWFkbWluQGZvcm1pLmNvLmluIhFnc2lfODE4NjA5XzQ3NzA2NTIOCAEQARgBKAIwATgBUAE\x3d');id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
      <webElementGuid>0fbcdb0b-92f6-41a3-8505-4b8d0e58a5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;qJTHM&quot;]</value>
      <webElementGuid>22f34b30-afb9-4607-98f6-07b8595952ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Weve got your back/iframe_OR_gsi_818609_477065</value>
      <webElementGuid>55ca82a3-e110-45ff-b2cc-77df905fc6b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>febbea4b-83e7-4e50-b73e-78e5948ab77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = concat(&quot;Sign in with GoogleSign in with Googlegis.provider.button.bootstrap(&quot; , &quot;'&quot; , &quot;CiIKFitMSHZuU1J5b2dwQkRkdHNpZGI5TkESBHdhcm4aAmVuGtgBCkkxMDM4MDc0Nzc0MjYyLWltNDVjaXAzdDBkcWw3ZzlqbDlyODk5YXM1ODVnYTd2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tEh1odHRwczovL29yZ2FuaXplci5mb3JtaS5jby5pbhoLZm9ybWkuY28uaW4qImh0dHBzOi8vZm9ybWkuY28uaW4vcHJpdmFjeS1wb2xpY3kyKGh0dHBzOi8vZm9ybWkuY28uaW4vdGVybXMtYW5kLWNvbmRpdGlvbnM6EWFkbWluQGZvcm1pLmNvLmluIhFnc2lfODE4NjA5XzQ3NzA2NTIOCAEQARgBKAIwATgBUAE\x3d&quot; , &quot;'&quot; , &quot;);id(&quot;katalon-rec_elementInfoDiv&quot;)&quot;) or . = concat(&quot;Sign in with GoogleSign in with Googlegis.provider.button.bootstrap(&quot; , &quot;'&quot; , &quot;CiIKFitMSHZuU1J5b2dwQkRkdHNpZGI5TkESBHdhcm4aAmVuGtgBCkkxMDM4MDc0Nzc0MjYyLWltNDVjaXAzdDBkcWw3ZzlqbDlyODk5YXM1ODVnYTd2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tEh1odHRwczovL29yZ2FuaXplci5mb3JtaS5jby5pbhoLZm9ybWkuY28uaW4qImh0dHBzOi8vZm9ybWkuY28uaW4vcHJpdmFjeS1wb2xpY3kyKGh0dHBzOi8vZm9ybWkuY28uaW4vdGVybXMtYW5kLWNvbmRpdGlvbnM6EWFkbWluQGZvcm1pLmNvLmluIhFnc2lfODE4NjA5XzQ3NzA2NTIOCAEQARgBKAIwATgBUAE\x3d&quot; , &quot;'&quot; , &quot;);id(&quot;katalon-rec_elementInfoDiv&quot;)&quot;))]</value>
      <webElementGuid>43e08dd0-bf10-4914-b65a-c1816720bc27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
