<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LoginRegister</name>
   <tag></tag>
   <elementGuidId>435aa4b6-04ea-4980-bd98-ff8ee34df07d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-row.public-navbar_navbar__eJzUB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>db183170-3e44-4a62-ae00-0fd71a822041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-row public-navbar_navbar__eJzUB</value>
      <webElementGuid>2539444a-3643-405f-8177-adb9b1f88b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginRegister</value>
      <webElementGuid>9d2128b2-f01c-4b54-ba4e-eaa2270d05ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;home-page_maincontainer__beomm&quot;]/div[@class=&quot;ant-row public-navbar_navbar__eJzUB&quot;]</value>
      <webElementGuid>54c89130-3759-4a78-b9e5-c97cbd6e9836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div</value>
      <webElementGuid>ce9192cf-cb57-41a8-b80a-ba1a72d51e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>fd6d3380-9d73-440d-bf39-6e0c05482b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LoginRegister' or . = 'LoginRegister')]</value>
      <webElementGuid>96e2ee57-bb8e-4206-8cef-c2d444da8278</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
