<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_OR_gsi_34095_328510</name>
   <tag></tag>
   <elementGuidId>031434bd-8fe6-45ec-823d-7694e8ecc307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsi_34095_328510']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gsi_34095_328510</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0b639eb2-f4d2-43e0-9bdd-cb20a74851ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;client_id=1038074774262-im45cip3t0dql7g9jl9r899as585ga7v.apps.googleusercontent.com&amp;iframe_id=gsi_34095_328510&amp;as=W+SITw5YojL%2FRrhc7u2kfA</value>
      <webElementGuid>b78f59d9-8268-4ebd-b8dc-a925d6fdd083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsi_34095_328510</value>
      <webElementGuid>a1f3aff3-91b5-4ff7-9bc3-ec62898c81ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign in with Google Button</value>
      <webElementGuid>2f5b9ec5-84a1-4605-adad-7f10f5df56fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsi_34095_328510&quot;)</value>
      <webElementGuid>a55c39ef-250b-4051-8951-2954452d9789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsi_34095_328510']</value>
      <webElementGuid>f03080c7-6065-4cb9-85a9-199b532cdf8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signindiv']/div/iframe</value>
      <webElementGuid>0c0f1fb0-145b-4db4-87e3-f04844207005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>408f6e04-0e8a-48d7-8d51-25d1a28adbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;client_id=1038074774262-im45cip3t0dql7g9jl9r899as585ga7v.apps.googleusercontent.com&amp;iframe_id=gsi_34095_328510&amp;as=W+SITw5YojL%2FRrhc7u2kfA' and @id = 'gsi_34095_328510' and @title = 'Sign in with Google Button']</value>
      <webElementGuid>1c51d33c-f69e-4482-8479-19bf3141b3fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
