<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_OR_gsi_892247_211837</name>
   <tag></tag>
   <elementGuidId>e5a5983f-dc2e-4ffa-a6fa-2cc2beb47f46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsi_892247_211837']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gsi_892247_211837</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5908fee9-84ca-450e-8957-bb929c3d7e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;client_id=1038074774262-im45cip3t0dql7g9jl9r899as585ga7v.apps.googleusercontent.com&amp;iframe_id=gsi_892247_211837&amp;as=A2BdpoZSRJQeeFq6Db2WzQ</value>
      <webElementGuid>912bdcce-f0be-4963-ab90-04bc1e08ee65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsi_892247_211837</value>
      <webElementGuid>64717a15-af36-41ce-9674-2581558ab0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign in with Google Button</value>
      <webElementGuid>163e734b-5a03-4e96-8246-2af0ee490e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsi_892247_211837&quot;)</value>
      <webElementGuid>fcdeda51-aaf2-484a-b50e-c19c5d226804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsi_892247_211837']</value>
      <webElementGuid>325a65d9-3cd6-4db4-ba37-737f0ebc74a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signindiv']/div/iframe</value>
      <webElementGuid>08d1ac93-fdc4-4095-8dfd-ebbb0cb4d7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d4d8e1ed-392b-4a28-8fe1-92f21f1e7571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;client_id=1038074774262-im45cip3t0dql7g9jl9r899as585ga7v.apps.googleusercontent.com&amp;iframe_id=gsi_892247_211837&amp;as=A2BdpoZSRJQeeFq6Db2WzQ' and @id = 'gsi_892247_211837' and @title = 'Sign in with Google Button']</value>
      <webElementGuid>bc4a1f0c-8e66-4c85-a74f-940eded2e5e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
