<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_OR_gsi_921655_789516</name>
   <tag></tag>
   <elementGuidId>2b8bbbe3-a76f-4b41-87e4-a46c4c071a18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsi_921655_789516']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gsi_921655_789516</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6a545a3d-6cd6-4b8f-ab22-ed46ec5f0280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;client_id=1038074774262-im45cip3t0dql7g9jl9r899as585ga7v.apps.googleusercontent.com&amp;iframe_id=gsi_921655_789516&amp;as=QlgApYkNF7OlLc3iwGs1cw</value>
      <webElementGuid>d6c7a078-accf-41e8-82ce-772cdc2475c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsi_921655_789516</value>
      <webElementGuid>5b171561-9666-48bf-9ae6-ff72a180bb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign in with Google Button</value>
      <webElementGuid>05187c8b-941d-4845-8245-24ebab1b07f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsi_921655_789516&quot;)</value>
      <webElementGuid>f99a0dc6-8b5b-465e-9c37-df8d94d730d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsi_921655_789516']</value>
      <webElementGuid>abc64b97-4287-482a-8b1f-dc76711252d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signindiv']/div/iframe</value>
      <webElementGuid>f88e31fb-8d30-42c3-8447-5bd988190d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8a15f70f-8580-4b1c-bc88-39dde11b6df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;client_id=1038074774262-im45cip3t0dql7g9jl9r899as585ga7v.apps.googleusercontent.com&amp;iframe_id=gsi_921655_789516&amp;as=QlgApYkNF7OlLc3iwGs1cw' and @id = 'gsi_921655_789516' and @title = 'Sign in with Google Button']</value>
      <webElementGuid>276f1553-86a7-4802-a2f0-416c18502ee1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
