<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_OR_gsi_137037_405235</name>
   <tag></tag>
   <elementGuidId>8d804e8b-4cca-4e14-aa72-de049d8278aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gsi_137037_405235</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsi_137037_405235']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b7738170-4273-42a0-9239-925b8fcd09a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;client_id=1038074774262-im45cip3t0dql7g9jl9r899as585ga7v.apps.googleusercontent.com&amp;iframe_id=gsi_137037_405235&amp;as=5aWozXxrkqLhn0UyaZNFqA</value>
      <webElementGuid>741515a4-b2f2-4110-bc59-64245abc3cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsi_137037_405235</value>
      <webElementGuid>63154653-9bfa-49ea-87ff-a3b173bad212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign in with Google Button</value>
      <webElementGuid>53ce9bb4-c146-439d-be74-2247f45722a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsi_137037_405235&quot;)</value>
      <webElementGuid>1794dda7-73ca-4435-b3c5-eba218c1af1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsi_137037_405235']</value>
      <webElementGuid>ae96c06b-7f19-4af4-8216-3bfb3e16dee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signindiv']/div/iframe</value>
      <webElementGuid>5e9cef1f-4414-4152-b13e-617f0f857d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>58483d7e-4cfc-4af5-b2a3-94a6a2497197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;client_id=1038074774262-im45cip3t0dql7g9jl9r899as585ga7v.apps.googleusercontent.com&amp;iframe_id=gsi_137037_405235&amp;as=5aWozXxrkqLhn0UyaZNFqA' and @id = 'gsi_137037_405235' and @title = 'Sign in with Google Button']</value>
      <webElementGuid>e4ea9d13-e154-41af-b50e-92b060088a99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
