<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Register</name>
   <tag></tag>
   <elementGuidId>092c981f-7740-4109-b985-456be7328402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-default.auth_registerbutton__muBzB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e266a56c-d6ad-4d60-805d-1f51600f1011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>registermainbutton</value>
      <webElementGuid>b29e3436-7f6e-45b0-bb06-7f19f89f180b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89a4e21f-6bf1-4e0e-bbec-c780382e9867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default auth_registerbutton__muBzB</value>
      <webElementGuid>5998118a-2df5-49f8-8ccf-b9a8226f2b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>15db69e9-5f25-48e9-ab08-951004635729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;auth_parent__StwOh&quot;]/div[@class=&quot;auth_maincontainer__9gUqq&quot;]/div[@class=&quot;auth_leftside__m7fUv&quot;]/div[@class=&quot;auth_content__gR1Ij&quot;]/div[@class=&quot;auth_buttoncontainer__kxL4z&quot;]/button[@class=&quot;ant-btn ant-btn-default auth_registerbutton__muBzB&quot;]</value>
      <webElementGuid>13d49e61-1041-47c4-8084-b5e8d3a2d29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e9963d0-da7f-46db-8878-7baf0700f379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>registermainbutton</value>
      <webElementGuid>14372753-bdfa-424c-a5f7-6141912bb65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77c6f444-d7d7-4cc4-a701-8672c773d410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default auth_registerbutton__muBzB</value>
      <webElementGuid>bd466873-c854-4a76-8c67-34db476a62f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>d8e08810-c5f3-43d0-89c8-bd10c14883e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;auth_parent__StwOh&quot;]/div[@class=&quot;auth_maincontainer__9gUqq&quot;]/div[@class=&quot;auth_leftside__m7fUv&quot;]/div[@class=&quot;auth_content__gR1Ij&quot;]/div[@class=&quot;auth_buttoncontainer__kxL4z&quot;]/button[@class=&quot;ant-btn ant-btn-default auth_registerbutton__muBzB&quot;]</value>
      <webElementGuid>1a500e82-ac7d-49c6-99d4-db680325bfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7a877da-2740-4c9d-9b94-0b5d57bcc6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>registermainbutton</value>
      <webElementGuid>2bbbc13b-695c-46b7-a375-cb238c45573d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ccb5a1f9-2c6d-4d57-8d27-1e6f6695f378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default auth_registerbutton__muBzB</value>
      <webElementGuid>3d516936-7dec-4680-ad09-936b6b425345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>f31831ab-4b62-4e82-8f86-19b3bad3bb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;auth_parent__StwOh&quot;]/div[@class=&quot;auth_maincontainer__9gUqq&quot;]/div[@class=&quot;auth_leftside__m7fUv&quot;]/div[@class=&quot;auth_content__gR1Ij&quot;]/div[@class=&quot;auth_buttoncontainer__kxL4z&quot;]/button[@class=&quot;ant-btn ant-btn-default auth_registerbutton__muBzB&quot;]</value>
      <webElementGuid>49a5ea9d-3f5f-4f87-9dac-73a6b03f3781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35c4a259-6048-449f-b3e7-22cc799c89aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>registermainbutton</value>
      <webElementGuid>9a902fb2-4d82-4161-943e-4e7ba1538396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>83ff3057-03fd-4a28-a2df-d4272465475a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default auth_registerbutton__muBzB</value>
      <webElementGuid>78569520-77ea-4dd6-85b0-1ddd16368a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>b2ddf428-f822-43e0-893b-cb79b85e500c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;auth_parent__StwOh&quot;]/div[@class=&quot;auth_maincontainer__9gUqq&quot;]/div[@class=&quot;auth_leftside__m7fUv&quot;]/div[@class=&quot;auth_content__gR1Ij&quot;]/div[@class=&quot;auth_buttoncontainer__kxL4z&quot;]/button[@class=&quot;ant-btn ant-btn-default auth_registerbutton__muBzB&quot;]</value>
      <webElementGuid>5fc7fc31-e45e-47a2-8d48-73a3d68ddbba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>cd39edc5-3067-4818-a4a9-d3d125ac9940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>f9622615-7dc5-4ed9-b2ef-24db8fdf65b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discover the best events &amp; parties happening around the town,curated just for you.'])[1]/following::button[1]</value>
      <webElementGuid>43d5b353-a614-4455-a235-4e6db24539ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOT JUST ANOTHER TICKETING PLATFORM'])[1]/following::button[1]</value>
      <webElementGuid>dc6128db-c4d9-4a0f-8478-6437778c99ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/preceding::button[1]</value>
      <webElementGuid>3fb0a0fa-3992-47f6-a63f-4f2cc45e33a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c1356321-b650-4aa3-a1b7-570e8ac129d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>df558608-ccae-4e9b-94e3-3958c03847b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
