<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign In</name>
   <tag></tag>
   <elementGuidId>ec665614-ffec-47fa-913f-5a46ffabac06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[2]/div[3]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.auth_signin__JqwQG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43eb7c7b-9842-478d-8c7c-df0ebe62783a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>signinmainbutton</value>
      <webElementGuid>cb2da988-8eed-4d2a-b9b2-2dbdfddadef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth_signin__JqwQG</value>
      <webElementGuid>94198fe8-4753-46c6-b5f9-dd2fef41afbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>bc5496ff-4e7c-40e6-bd1f-a52e57347f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;auth_parent__StwOh&quot;]/div[@class=&quot;auth_maincontainer__9gUqq&quot;]/div[@class=&quot;auth_leftside__m7fUv&quot;]/div[@class=&quot;auth_content__gR1Ij&quot;]/div[@class=&quot;auth_alreadyuser__Wl8r8&quot;]/span[@class=&quot;auth_signin__JqwQG&quot;]</value>
      <webElementGuid>971d8866-5c3e-42c7-b252-5d0dc65ea18b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[3]/span[2]</value>
      <webElementGuid>dffb6106-ad08-4efb-a2c4-7a7fcf10c1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already a user?'])[1]/following::span[1]</value>
      <webElementGuid>1469707e-8044-4212-aee1-76bfe476a436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/following::span[2]</value>
      <webElementGuid>6ab8aef4-0746-4ac7-b755-0c4e79d0b0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Magazine'])[1]/preceding::span[1]</value>
      <webElementGuid>1017c8b8-1e18-4688-b251-dc617248155f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Event'])[1]/preceding::span[1]</value>
      <webElementGuid>bbc233f2-20c2-4731-909c-ae9d0ff4e6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign In']/parent::*</value>
      <webElementGuid>1df98698-194d-4414-85af-48f7c26d91c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>461506b0-5561-4641-8df6-72dc37bddadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>0b73c27c-8fb5-46cc-93dc-dff101d29ccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
