<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_Sign in with GoogleSign in with Google_14d819</name>
   <tag></tag>
   <elementGuidId>d902235d-66ea-45ea-b51f-8e82d79bd33b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body.qJTHM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>91213f34-c753-45b3-93ae-abc4692245f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qJTHM</value>
      <webElementGuid>a9ea06bd-e7d8-4a59-a84d-381c423f952b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in with GoogleSign in with Googlegis.provider.button.bootstrap('CiIKFkc0VWpNNHBlc25tUng0ZE1rUDk5cEESBHdhcm4aAmVuGuABCkkxMDM4MDc0Nzc0MjYyLWltNDVjaXAzdDBkcWw3ZzlqbDlyODk5YXM1ODVnYTd2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tEiVodHRwczovL29yZ2FuaXplci10ZXN0aW5nLmZvcm1pLmNvLmluGgtmb3JtaS5jby5pbioiaHR0cHM6Ly9mb3JtaS5jby5pbi9wcml2YWN5LXBvbGljeTIoaHR0cHM6Ly9mb3JtaS5jby5pbi90ZXJtcy1hbmQtY29uZGl0aW9uczoRYWRtaW5AZm9ybWkuY28uaW4iEWdzaV81NTMxMDdfODk4OTExMg4IARABGAEoAjABOAFQAQ\x3d\x3d');id(&quot;container&quot;)/div[@class=&quot;nsm7Bb-HzV7m-LgbsSe  hJDwNd-SxQuSe i5vt6e-Ia7Qfc uaxL4e-RbRzK&quot;]/div[@class=&quot;nsm7Bb-HzV7m-LgbsSe-bN97Pc-sM5MNb&quot;]</value>
      <webElementGuid>2cb3b1d5-be26-4fd1-aafb-8937044e3bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;qJTHM&quot;]</value>
      <webElementGuid>2002236c-8199-433b-b4dd-1b75537b2223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Sign-up to get the Formi dashboard/iframe_OR_gsi_553107_898911</value>
      <webElementGuid>112d24e9-fbd0-4b79-9bba-5e114eb78ce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>e0c239c6-b751-405a-9fa9-c76699956fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = concat(&quot;Sign in with GoogleSign in with Googlegis.provider.button.bootstrap(&quot; , &quot;'&quot; , &quot;CiIKFkc0VWpNNHBlc25tUng0ZE1rUDk5cEESBHdhcm4aAmVuGuABCkkxMDM4MDc0Nzc0MjYyLWltNDVjaXAzdDBkcWw3ZzlqbDlyODk5YXM1ODVnYTd2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tEiVodHRwczovL29yZ2FuaXplci10ZXN0aW5nLmZvcm1pLmNvLmluGgtmb3JtaS5jby5pbioiaHR0cHM6Ly9mb3JtaS5jby5pbi9wcml2YWN5LXBvbGljeTIoaHR0cHM6Ly9mb3JtaS5jby5pbi90ZXJtcy1hbmQtY29uZGl0aW9uczoRYWRtaW5AZm9ybWkuY28uaW4iEWdzaV81NTMxMDdfODk4OTExMg4IARABGAEoAjABOAFQAQ\x3d\x3d&quot; , &quot;'&quot; , &quot;);id(&quot;container&quot;)/div[@class=&quot;nsm7Bb-HzV7m-LgbsSe  hJDwNd-SxQuSe i5vt6e-Ia7Qfc uaxL4e-RbRzK&quot;]/div[@class=&quot;nsm7Bb-HzV7m-LgbsSe-bN97Pc-sM5MNb&quot;]&quot;) or . = concat(&quot;Sign in with GoogleSign in with Googlegis.provider.button.bootstrap(&quot; , &quot;'&quot; , &quot;CiIKFkc0VWpNNHBlc25tUng0ZE1rUDk5cEESBHdhcm4aAmVuGuABCkkxMDM4MDc0Nzc0MjYyLWltNDVjaXAzdDBkcWw3ZzlqbDlyODk5YXM1ODVnYTd2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tEiVodHRwczovL29yZ2FuaXplci10ZXN0aW5nLmZvcm1pLmNvLmluGgtmb3JtaS5jby5pbioiaHR0cHM6Ly9mb3JtaS5jby5pbi9wcml2YWN5LXBvbGljeTIoaHR0cHM6Ly9mb3JtaS5jby5pbi90ZXJtcy1hbmQtY29uZGl0aW9uczoRYWRtaW5AZm9ybWkuY28uaW4iEWdzaV81NTMxMDdfODk4OTExMg4IARABGAEoAjABOAFQAQ\x3d\x3d&quot; , &quot;'&quot; , &quot;);id(&quot;container&quot;)/div[@class=&quot;nsm7Bb-HzV7m-LgbsSe  hJDwNd-SxQuSe i5vt6e-Ia7Qfc uaxL4e-RbRzK&quot;]/div[@class=&quot;nsm7Bb-HzV7m-LgbsSe-bN97Pc-sM5MNb&quot;]&quot;))]</value>
      <webElementGuid>3b50757c-743e-40b5-83f2-06d5c034cace</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
