<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign in with Google_nsm7Bb-HzV7m-LgbsSe-MJoBVe</name>
   <tag></tag>
   <elementGuidId>5d3e9fbe-4495-4144-a8f9-4c065764a13b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nsm7Bb-HzV7m-LgbsSe-MJoBVe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c7ab1b3-be3e-4a30-a8c4-c84481f56a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nsm7Bb-HzV7m-LgbsSe-MJoBVe</value>
      <webElementGuid>7e5a1668-65fa-4718-a4a3-86bca5179281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;nsm7Bb-HzV7m-LgbsSe  hJDwNd-SxQuSe i5vt6e-Ia7Qfc uaxL4e-RbRzK&quot;]/div[@class=&quot;nsm7Bb-HzV7m-LgbsSe-MJoBVe&quot;]</value>
      <webElementGuid>2161c8bc-9fb5-46b4-a186-38a422ed0e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Sign-up to get the Formi dashboard/iframe_OR_gsi_553107_898911</value>
      <webElementGuid>e534899f-c091-4c4c-8530-cf519f8109e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div</value>
      <webElementGuid>149d7e23-3244-4ea0-9c39-7f05155516f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>f5d3c815-4e2e-41b7-98d3-2d4e79eb7b90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
