<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_registerEmail AddressInvalid email form_3972ad</name>
   <tag></tag>
   <elementGuidId>a56ebba4-c6c8-4dd0-ad50-eaa6df86663a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/form/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.register_parent__t4evr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f60078db-2bea-4239-ae2b-34167b8abc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register_parent__t4evr</value>
      <webElementGuid>80eb69c3-7ee7-41b1-9c5a-c7f1e08cdb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>registerEmail AddressInvalid email format!Create PasswordORNext</value>
      <webElementGuid>5009fe5b-9675-472f-8da7-88c999be66c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/form[@class=&quot;ant-form ant-form-horizontal&quot;]/div[@class=&quot;register_maincontainer__W6PYh&quot;]/div[@class=&quot;register_parent__t4evr&quot;]</value>
      <webElementGuid>7b59ec83-9808-4fa7-9903-636ecb9afa4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/form/div[2]/div</value>
      <webElementGuid>814f7eae-ced4-4ecf-b203-ec7bf701d368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::div[3]</value>
      <webElementGuid>27bc3bb5-2b2d-4457-bd81-914af172308f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[3]</value>
      <webElementGuid>606e95d7-589f-4794-9b05-b7c03f63ce70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div</value>
      <webElementGuid>53359cb0-7590-47c4-bea8-bfd29a37ffee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'registerEmail AddressInvalid email format!Create PasswordORNext' or . = 'registerEmail AddressInvalid email format!Create PasswordORNext')]</value>
      <webElementGuid>559cfe99-7271-4a47-b598-f4652fd35306</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
