<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_registerEmail AddressCreate PasswordOR</name>
   <tag></tag>
   <elementGuidId>c345d4bc-7650-4c03-be73-903923e7846d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.register_step1__V4kmE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/form/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e837a31d-ce45-4f4e-ba83-022c94162164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register_step1__V4kmE</value>
      <webElementGuid>bc82758b-35f4-4830-ad36-8502dd971987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>registerEmail AddressCreate PasswordOR</value>
      <webElementGuid>87029b36-38d4-4e01-a206-0ec636d307b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/form[@class=&quot;ant-form ant-form-horizontal&quot;]/div[@class=&quot;register_maincontainer__W6PYh&quot;]/div[@class=&quot;register_parent__t4evr&quot;]/div[@class=&quot;register_main_wrapper__MM_VK&quot;]/div[@class=&quot;register_step1__V4kmE&quot;]</value>
      <webElementGuid>a5117876-9ef0-478d-b621-c7e4dde02b69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/form/div[2]/div/div/div</value>
      <webElementGuid>32ab82c0-fc97-42b2-8f1b-b9cb918f8a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::div[5]</value>
      <webElementGuid>adfd7a2b-9084-4164-8768-2017cbb30ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[5]</value>
      <webElementGuid>5eee4ace-cc56-4efa-92f1-c6e9d9e1a9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>cec321b4-157f-4673-8ed2-17b74f3c1dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'registerEmail AddressCreate PasswordOR' or . = 'registerEmail AddressCreate PasswordOR')]</value>
      <webElementGuid>c0dbffce-4386-41d3-85e0-e0425570cc8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
