<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_OR_gsi_629536_177115</name>
   <tag></tag>
   <elementGuidId>f9ae349f-ca19-4c30-8c26-eb4dead3950c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsi_629536_177115']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gsi_629536_177115</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>05be5ca7-93b4-4258-bed2-d4533b44b6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;client_id=1038074774262-im45cip3t0dql7g9jl9r899as585ga7v.apps.googleusercontent.com&amp;iframe_id=gsi_629536_177115&amp;as=4jbtkvUUu+SQFqXp7eG3cg</value>
      <webElementGuid>caf69f1a-659c-44d3-9c15-da0c84c9aa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsi_629536_177115</value>
      <webElementGuid>7c2ee8c0-7cbe-4006-b897-30a18360cbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign in with Google Button</value>
      <webElementGuid>3807aab9-514f-4f13-bbc2-18a70a5e7eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsi_629536_177115&quot;)</value>
      <webElementGuid>aae71de9-9deb-4e60-bc9e-f0eb5a6d1b08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsi_629536_177115']</value>
      <webElementGuid>f6d1946b-a7da-476c-b990-39c3b0d1879a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signindiv']/div/iframe</value>
      <webElementGuid>7310d533-5241-448b-8198-e8ce799b8cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>18540751-b270-409f-8a8e-a6ec64c0197a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;client_id=1038074774262-im45cip3t0dql7g9jl9r899as585ga7v.apps.googleusercontent.com&amp;iframe_id=gsi_629536_177115&amp;as=4jbtkvUUu+SQFqXp7eG3cg' and @id = 'gsi_629536_177115' and @title = 'Sign in with Google Button']</value>
      <webElementGuid>f9ae114a-9df3-4043-91d5-258952767eaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
