<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Welcome to Organizer DashboardTrack, ma_064a6f</name>
   <tag></tag>
   <elementGuidId>51ae31c1-a090-453e-8899-1b2163c75caa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.organizer-dashboard_mainSection__y7Jve</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7dd23a8f-b015-42ec-becc-67055643959d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>organizer-dashboard_mainSection__y7Jve</value>
      <webElementGuid>070b6cc2-456d-4c84-85de-8fb327ddb8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome to Organizer DashboardTrack, manage and automate payments of your team members. Create EventVerify Code Invite MemberEducational content to boost your sales, coming soon.Laborum possimus repudiandae id corporis suscipit ut.Asperiores velit similique incidunt dicta. Ipsum libero numquam porro inventore. Minima odit sequi facere doloremque. Perspiciatis doloremque quasi asperiores consequatur tenetur rerum.Learn moreAll EventsOwn EventsPartnered Eventsdhanush sWednesday, November 23rd, 2:45 amtestCopy LinkGo To Dashboardevent 2 glWednesday, November 23rd, 1:00 amkalingaCopy LinkGo To DashboardFatman 2021 || DJ ShaanWednesday, November 16th, 1:15 amXU - Fashion Bar KitchenCopy LinkGo To DashboardOnderkoffer - International ActWednesday, November 30th, 1:15 amgyltCopy LinkGo To DashboardSutra reloadedFriday, December 9th, 1:45 amsutraCopy LinkGo To Dashboard</value>
      <webElementGuid>4a148e46-bcc0-4bbf-8008-68bf0a6d8566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;ant-row organizer-dashboard_dashboard__zwPV_&quot;]/div[@class=&quot;ant-col ant-col-24 organizer-dashboard_rightside__9SYiZ&quot;]/div[@class=&quot;organizer-dashboard_mainSection__y7Jve&quot;]</value>
      <webElementGuid>5c7dfbd0-6737-4ed4-b678-a7a060492313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[3]</value>
      <webElementGuid>766a7cea-21e6-467f-865d-39d1ee7e0728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blogs'])[1]/following::div[1]</value>
      <webElementGuid>29fa662a-333d-4923-9343-c1578a42cc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Events'])[1]/following::div[2]</value>
      <webElementGuid>28582151-830d-4c6e-8aa1-61837bb71e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]</value>
      <webElementGuid>afddf6b0-9aa5-4c00-bf46-15bddf5598e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Welcome to Organizer DashboardTrack, manage and automate payments of your team members. Create EventVerify Code Invite MemberEducational content to boost your sales, coming soon.Laborum possimus repudiandae id corporis suscipit ut.Asperiores velit similique incidunt dicta. Ipsum libero numquam porro inventore. Minima odit sequi facere doloremque. Perspiciatis doloremque quasi asperiores consequatur tenetur rerum.Learn moreAll EventsOwn EventsPartnered Eventsdhanush sWednesday, November 23rd, 2:45 amtestCopy LinkGo To Dashboardevent 2 glWednesday, November 23rd, 1:00 amkalingaCopy LinkGo To DashboardFatman 2021 || DJ ShaanWednesday, November 16th, 1:15 amXU - Fashion Bar KitchenCopy LinkGo To DashboardOnderkoffer - International ActWednesday, November 30th, 1:15 amgyltCopy LinkGo To DashboardSutra reloadedFriday, December 9th, 1:45 amsutraCopy LinkGo To Dashboard' or . = 'Welcome to Organizer DashboardTrack, manage and automate payments of your team members. Create EventVerify Code Invite MemberEducational content to boost your sales, coming soon.Laborum possimus repudiandae id corporis suscipit ut.Asperiores velit similique incidunt dicta. Ipsum libero numquam porro inventore. Minima odit sequi facere doloremque. Perspiciatis doloremque quasi asperiores consequatur tenetur rerum.Learn moreAll EventsOwn EventsPartnered Eventsdhanush sWednesday, November 23rd, 2:45 amtestCopy LinkGo To Dashboardevent 2 glWednesday, November 23rd, 1:00 amkalingaCopy LinkGo To DashboardFatman 2021 || DJ ShaanWednesday, November 16th, 1:15 amXU - Fashion Bar KitchenCopy LinkGo To DashboardOnderkoffer - International ActWednesday, November 30th, 1:15 amgyltCopy LinkGo To DashboardSutra reloadedFriday, December 9th, 1:45 amsutraCopy LinkGo To Dashboard')]</value>
      <webElementGuid>34f3bf53-5d5e-4da0-9423-8051cd97db18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
