<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Show password</name>
   <tag></tag>
   <elementGuidId>64ab70b8-a3a2-4cd2-992e-9f39a99bf436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectioni1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selectioni1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;selectioni1&quot;)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f6b69c66-d84a-4a03-b473-7720191ce045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectioni1</value>
      <webElementGuid>cb786619-3e12-40ed-8df4-3f78a16af1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d3GVvd jGAaxb</value>
      <webElementGuid>8cfa4dfd-d83c-4a97-8824-0f69d4f11073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>CeL6Qc</value>
      <webElementGuid>8a2d1f40-0307-455a-bd05-a8697c5d196e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show password</value>
      <webElementGuid>d3390d37-4fc2-4bda-8c7c-201f0ca17043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectioni1&quot;)</value>
      <webElementGuid>45614143-ade5-40d4-97cb-0cb53d727a1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='selectioni1']</value>
      <webElementGuid>7a9ff3dd-a10f-4da4-9327-0e3281c61cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_container']/div/div/div[2]/div/div/div/form/span/section/div/div/div[3]/div[3]/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>3fdf4d51-a787-4bab-9ab8-cd592076ff3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use 8 or more characters with a mix of letters, numbers &amp; symbols'])[1]/following::div[14]</value>
      <webElementGuid>26c000be-3a82-4bbe-a103-6c3754a62664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use my current email address instead'])[1]/following::div[40]</value>
      <webElementGuid>a2d17102-9f09-4c70-b119-3b9ee6141583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::div[7]</value>
      <webElementGuid>9fd89dca-e921-498e-8171-5b82a08e4b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in instead'])[1]/preceding::div[13]</value>
      <webElementGuid>c2d2994d-e5b5-46ab-8c6b-72c455482692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show password']/parent::*</value>
      <webElementGuid>8dbdc897-1b78-4b85-a4c1-dbdb6d2d0782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>55cd8800-e4d5-4a99-bfe0-651320183065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'selectioni1' and (text() = 'Show password' or . = 'Show password')]</value>
      <webElementGuid>8736ac90-dff6-4fb0-84bb-a2b583e5e96b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
