<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create your Google AccountFirst nameLas_d2fe9d</name>
   <tag></tag>
   <elementGuidId>70771bb4-5fe8-4e89-a29a-af5a682d6f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='initialView']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.xkfVF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3e8e4378-5bca-4ffb-8fde-85d2335ffbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xkfVF</value>
      <webElementGuid>68249cc4-5bab-4b54-bf0e-b0b5a0ee6bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>f2d3ae</value>
      <webElementGuid>ddba1da3-ebf5-4404-ab5f-160558ce563a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>bdb87a0c-7f8a-4468-80ab-cbddace64352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create your Google AccountFirst nameLast nameUsername@gmail.comYou can use letters, numbers &amp; periodsUse my current email address insteadPasswordConfirmUse 8 or more characters with a mix of letters, numbers &amp; symbolsShow passwordNextSign in insteadOne account. All of Google working for you.</value>
      <webElementGuid>e0751774-8f82-4639-b372-3e920c98ac92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;initialView&quot;)/div[@class=&quot;xkfVF&quot;]</value>
      <webElementGuid>6b5623bd-a542-4596-8eb3-aff81fbd84ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='initialView']/div[2]</value>
      <webElementGuid>70b87952-20be-41ea-ba43-0e88e743f9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]</value>
      <webElementGuid>ec95af64-5451-4d72-a403-d26508fc94ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Create your Google AccountFirst nameLast nameUsername@gmail.comYou can use letters, numbers &amp; periodsUse my current email address insteadPasswordConfirmUse 8 or more characters with a mix of letters, numbers &amp; symbolsShow passwordNextSign in insteadOne account. All of Google working for you.' or . = 'Create your Google AccountFirst nameLast nameUsername@gmail.comYou can use letters, numbers &amp; periodsUse my current email address insteadPasswordConfirmUse 8 or more characters with a mix of letters, numbers &amp; symbolsShow passwordNextSign in insteadOne account. All of Google working for you.')]</value>
      <webElementGuid>325c8f29-e30e-49ae-a507-b4576905c6cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
