<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>otp4</name>
   <tag></tag>
   <elementGuidId>5794c102-d72a-43d5-bcc1-d8a1cb7a5ad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.column.column-5 > table.heading_block.block-2 > tbody > tr > td.pad > h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/main/div/div/div/div/article/div/div[3]/span/table/tbody/tr/td/table[2]/tbody/tr/td/table/tbody/tr/td[5]/table/tbody/tr/td/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f9d88536-d4e9-4ec8-9cff-fd51d8de587c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1896d1bd-b71d-40e9-838b-6012289ce789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;wrapper&quot;]/main[@class=&quot;content active with-advert&quot;]/div[@class=&quot;scrollview __vuescroll hasVBar vBarVisible mouseEnter&quot;]/div[@class=&quot;__panel&quot;]/div[@class=&quot;__view&quot;]/div[@class=&quot;content__wrapper&quot;]/article[@class=&quot;message&quot;]/div[1]/div[@class=&quot;message__content&quot;]/span[1]/table[@class=&quot;nl-container&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;row row-2&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;row-content&quot;]/tbody[1]/tr[1]/td[@class=&quot;column column-5&quot;]/table[@class=&quot;heading_block block-2&quot;]/tbody[1]/tr[1]/td[@class=&quot;pad&quot;]/h1[1]</value>
      <webElementGuid>69189706-c68e-47c2-9942-caaa84ba47d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div/div/div/div/article/div/div[3]/span/table/tbody/tr/td/table[2]/tbody/tr/td/table/tbody/tr/td[5]/table/tbody/tr/td/h1</value>
      <webElementGuid>0c76b76f-cf30-4631-8e01-df3c47df9ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mark as unread'])[1]/following::h1[5]</value>
      <webElementGuid>f1f93151-8cce-4286-8abb-db8e091a5e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::h1[5]</value>
      <webElementGuid>59514eb9-8bce-4ec3-b227-5d067cf08463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::h1[2]</value>
      <webElementGuid>d41050e5-25cd-4c96-90c5-82e479d1ea22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose language'])[1]/preceding::h1[2]</value>
      <webElementGuid>cac7be26-82a6-42a7-afdb-9b28c6e98a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td/h1</value>
      <webElementGuid>292f177a-7413-4e79-bfcd-25eba9dd5fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '3' or . = '3')]</value>
      <webElementGuid>f12ed060-3f78-44ef-8d22-8ab2a273184d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
