<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Refresh</name>
   <tag></tag>
   <elementGuidId>9c11e2d8-59a0-4449-91a7-63671ef63ac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/div/div[2]/nav/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ab3600e9-4d94-49f4-bd8d-7c21000f07e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/</value>
      <webElementGuid>857cf0e3-73a1-4755-ab9a-007a2e63765e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>60ba5038-afc2-4061-a096-2a90e925a776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group dark:hover:text-white dark:hover:bg-gray-800 dark:focus:outline-none dark:focus:text-white dark:focus:bg-gray-800 flex items-center mt-1 px-2 py-2 dark:text-gray-300 text-gray-600 hover:text-gray-900 text-sm font-medium leading-5 hover:bg-gray-50 rounded-md transition nuxt-link-exact-active nuxt-link-active</value>
      <webElementGuid>b86fa27a-22fa-49db-b365-6709f0d9816a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Refresh
          </value>
      <webElementGuid>e502600c-0112-45b2-904c-19f940170253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;flex h-screen antialiased bg-gray-100 dark:bg-gray-900 overflow-hidden&quot;]/div[@class=&quot;hidden md:flex md:flex-shrink-0&quot;]/div[@class=&quot;flex flex-col pb-4 pt-5 w-64 dark:bg-gray-900 bg-white border-r border-gray-200 dark:border-gray-700 overflow-y-auto&quot;]/div[@class=&quot;flex flex-1 flex-col mb-2 mt-5 px-2&quot;]/nav[@class=&quot;flex-1&quot;]/a[@class=&quot;group dark:hover:text-white dark:hover:bg-gray-800 dark:focus:outline-none dark:focus:text-white dark:focus:bg-gray-800 flex items-center mt-1 px-2 py-2 dark:text-gray-300 text-gray-600 hover:text-gray-900 text-sm font-medium leading-5 hover:bg-gray-50 rounded-md transition nuxt-link-exact-active nuxt-link-active&quot;]</value>
      <webElementGuid>f94c70d0-9ab1-4f1f-a294-330a57de0b55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div[2]/nav/a[2]</value>
      <webElementGuid>e35fd6a1-162e-4437-83a5-8d3682567523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Refresh')]</value>
      <webElementGuid>c77ff778-2752-4e85-abe5-e46cb08c17cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inbox'])[1]/following::a[1]</value>
      <webElementGuid>e7684b85-dfcd-462f-9dfc-cf646d248671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/preceding::a[2]</value>
      <webElementGuid>6a87ae82-4362-4053-8b8d-66a02e0b256b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/preceding::a[3]</value>
      <webElementGuid>80aaf176-b789-499f-b791-fa46166596c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refresh']/parent::*</value>
      <webElementGuid>0de1cf4a-15eb-4134-a412-290c2295ac93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/')])[3]</value>
      <webElementGuid>bc94f016-5920-4055-8fe9-7d979492a83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>8fbc86f9-fec8-44ac-b075-722b4b83dca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/' and (text() = '
            Refresh
          ' or . = '
            Refresh
          ')]</value>
      <webElementGuid>8860aa2b-e929-470f-b263-ca351982d9ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
