<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__fixed z-10 inset-0</name>
   <tag></tag>
   <elementGuidId>bcb46033-8584-48b5-ada3-0f7fa0f85237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div[2]/div[4]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;__layout&quot;)/div[@class=&quot;flex h-screen antialiased bg-gray-100 dark:bg-gray-900 overflow-hidden&quot;]/div[@class=&quot;flex flex-1 flex-col w-0 overflow-hidden&quot;]/div[@class=&quot;relative flex flex-shrink-0 items-center h-16 dark:bg-gray-900 bg-white border-b border-gray-200 dark:border-gray-700&quot;]/div[@class=&quot;flex flex-1 justify-between px-4&quot;]/div[@class=&quot;flex items-center sm:ml-4 md:ml-6&quot;]/div[@class=&quot;relative ml-4&quot;]/div[@class=&quot;fixed z-10 inset-0&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.fixed.z-10.inset-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0bbb25fc-1198-452b-b5f6-c009fae4da6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fixed z-10 inset-0</value>
      <webElementGuid>c9fcf9b6-dbff-44b9-8444-f95b502767c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;flex h-screen antialiased bg-gray-100 dark:bg-gray-900 overflow-hidden&quot;]/div[@class=&quot;flex flex-1 flex-col w-0 overflow-hidden&quot;]/div[@class=&quot;relative flex flex-shrink-0 items-center h-16 dark:bg-gray-900 bg-white border-b border-gray-200 dark:border-gray-700&quot;]/div[@class=&quot;flex flex-1 justify-between px-4&quot;]/div[@class=&quot;flex items-center sm:ml-4 md:ml-6&quot;]/div[@class=&quot;relative ml-4&quot;]/div[@class=&quot;fixed z-10 inset-0&quot;]</value>
      <webElementGuid>24ef045f-c078-4855-ab2f-3aa0617e0973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div[2]/div[4]/div</value>
      <webElementGuid>7ef67d78-939b-4d08-a3bc-84337a336e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div</value>
      <webElementGuid>7fe4d8ba-7ed0-48f9-a86c-8c5106d39142</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
