<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>fdf4e1ec-5955-4567-b19d-82f3cbd18877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;pro&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>08216196-d8c5-419e-a7b0-e8fd65ea3fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>pro</value>
      <webElementGuid>2adcab47-374b-40d2-a2a8-e392fe4d4490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7adea75a-30dc-4128-a43f-76b60a9f6e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48fdb912-bf93-459f-8c1b-d74f227c0230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5041a33-e0cb-494a-b594-9c390b600a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b98d095f-a60c-4579-bb34-5288644aaf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>df161def-1551-4d54-bf1a-51c6d9e1b2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>912ce81a-0f0e-4d43-a4e3-5b711b3777b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;dark&quot;]/body[1]/span[1]/div[@class=&quot;orp-player-wrapper orp-player-ivm-BR&quot;]/div[@class=&quot;orp-light-player-wrapper&quot;]/div[@class=&quot;orp-player-iframe&quot;]/div[@class=&quot;orp-light-player-wrapper orp-notMobile orp-init-loading&quot;]/div[@class=&quot;orp-proVideo orp-controls-wrapper orp-jsShow&quot;]/div[@class=&quot;orp-light-player-wrapper&quot;]/div[@class=&quot;orp-lp-holder orp-is-muted orp-fit-fill orp-isPlaying&quot;]/div[@class=&quot;orp-vpaid-container&quot;]/iframe[1]</value>
      <webElementGuid>d71b1cf6-be03-4f41-9789-0450d9d61432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/iframe</value>
      <webElementGuid>e6daffec-1723-47e2-be9f-72401d92b8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'pro']</value>
      <webElementGuid>649f5c0b-8312-418b-a416-04773068fc51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
