<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , goog_1033885711, , ))_goog_1033885711</name>
   <tag></tag>
   <elementGuidId>0c856c2f-103f-418e-bc77-91949e530829</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='goog_1033885711']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#goog_1033885711</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0d4acc45-95ef-418b-96c5-67382caa0d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://imasdk.googleapis.com/js/core/bridge3.547.0_en.html#goog_1033885711</value>
      <webElementGuid>d5667bbf-4641-482a-a816-adb636ffe418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay</value>
      <webElementGuid>86c290b1-e3b2-4367-ad4a-132d76b6ee39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goog_1033885711</value>
      <webElementGuid>79192add-b52a-48b3-9e3d-70e40b085651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>c963f55b-8721-460e-9aa2-d1d211f5267d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>225</value>
      <webElementGuid>aae3cd90-1e26-45cf-ba91-fb309b3b46ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goog_1033885711&quot;)</value>
      <webElementGuid>664795b8-d8b6-4356-a159-fce0f53971e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Temp Mail - Disposable Temporary and F_746997/iframe</value>
      <webElementGuid>fdb329db-3bbb-4c3b-be5b-f97ccfb56b42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='goog_1033885711']</value>
      <webElementGuid>a50f7ff9-2ed1-47af-ae68-768fd3d36b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>070dc444-37af-4916-8e2a-778a64d040c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://imasdk.googleapis.com/js/core/bridge3.547.0_en.html#goog_1033885711' and @id = 'goog_1033885711']</value>
      <webElementGuid>11093e9a-a744-4be2-b364-7e8c83c84434</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
