<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , google_ads_iframe_1518_6bac94</name>
   <tag></tag>
   <elementGuidId>ad1f5f9e-59c4-4c89-96bb-f8efcc978baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='google_ads_iframe_/15184186,22758166583/mail.tm_interstitial_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cf74a3ed-37b7-45d8-8cee-e87a6623e831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>66d61e2d-f4f6-4bcd-bf5b-378a05882f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bb9d51d4fc400cc975aa9073816e8288.safeframe.googlesyndication.com/safeframe/1-0-40/html/container.html</value>
      <webElementGuid>9f944892-a597-46e1-9c7f-5fbed3d06ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>google_ads_iframe_/15184186,22758166583/mail.tm_interstitial_0</value>
      <webElementGuid>1708a5f6-e019-4d67-8959-ff573015c825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3rd party ad content</value>
      <webElementGuid>e606e135-3412-4c48-a602-6822bc1f8c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>ebeb8fd2-af64-43ce-8ead-ca6b79ff67ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c5d2d574-ef4a-4afa-881a-f7600a58aefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c4982baf-1f8f-4ca3-a031-939d2e1e9823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-safeframe</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ebbf0d5-daf9-447f-9832-3d2ae3acf1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation</value>
      <webElementGuid>645b6b38-919c-444a-8a6e-dfc801701730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay</value>
      <webElementGuid>fd37f887-b7a6-47d5-a61b-ea9ca51dc2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>4c361d5c-612b-4097-82b0-d518911243fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>2bbdc7ab-0848-4a0b-af61-58819c16429f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>40da796c-350f-49e7-9d6c-59b8105eb936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-container-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d78c5521-d2a4-4698-995f-fd188cdcaa3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-complete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74132912-1f18-41af-8052-2720673a6b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;google_ads_iframe_/15184186,22758166583/mail.tm_interstitial_0&quot;)</value>
      <webElementGuid>73992bd5-9d57-4f0d-b4ec-123f6bfa3da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>78582f48-233b-46f2-b9a9-78d9def2df90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e064a64-f406-4747-b942-e5292294c34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://4ecaa7ce56e049af08389b9ff9b25647.safeframe.googlesyndication.com/safeframe/1-0-40/html/container.html</value>
      <webElementGuid>9ebd15e1-e1ce-4ba1-a75a-69d18bc0f0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>google_ads_iframe_/15184186,22758166583/mail.tm_interstitial_0</value>
      <webElementGuid>a724f5b6-21f9-49cb-b841-84941918acce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3rd party ad content</value>
      <webElementGuid>3818a06d-06b6-47d4-a794-cce961557daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>129ee7a9-7547-4637-bff6-31a6be6c0f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4817a93d-4454-45ec-abb7-0b250cccf2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>34cda25f-1f12-4a94-8aeb-22172b8c8c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-safeframe</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>658bd8fb-57f8-4a0b-b999-d21f52605c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation</value>
      <webElementGuid>506b6896-a056-4f7c-9806-2db8beafdb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay</value>
      <webElementGuid>5081fcab-cf35-40f3-bf0a-3f4f91d269d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>153ce612-ff65-451e-bc27-9ae388eb9c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>e1f126a2-eb87-490c-82f7-a66fa5f03e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>adcf1e53-cb03-4448-92e1-1f643505c6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-container-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>84fec581-2710-4137-8925-8a5089ef6ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-complete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a9db35f-68f4-42fb-a28a-1d5b3d04f850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;google_ads_iframe_/15184186,22758166583/mail.tm_interstitial_0&quot;)</value>
      <webElementGuid>e2a36a51-f237-4ca1-a6ed-37c73b9265c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='google_ads_iframe_/15184186,22758166583/mail.tm_interstitial_0']</value>
      <webElementGuid>1e5ce8c3-81aa-4b08-a9f8-57e1a6fbd9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='google_ads_iframe_/15184186,22758166583/mail.tm_interstitial_0__container__']/iframe</value>
      <webElementGuid>b4586286-0869-450c-976e-496f2ae74a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins/div/iframe</value>
      <webElementGuid>130e2532-cbbb-49f6-a281-c3c7aee8ef39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://bb9d51d4fc400cc975aa9073816e8288.safeframe.googlesyndication.com/safeframe/1-0-40/html/container.html' and @id = 'google_ads_iframe_/15184186,22758166583/mail.tm_interstitial_0' and @title = '3rd party ad content']</value>
      <webElementGuid>d060f59c-8e2e-4f27-a22a-1e9e1298ef58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://4ecaa7ce56e049af08389b9ff9b25647.safeframe.googlesyndication.com/safeframe/1-0-40/html/container.html' and @id = 'google_ads_iframe_/15184186,22758166583/mail.tm_interstitial_0' and @title = '3rd party ad content']</value>
      <webElementGuid>526cee4d-2671-4285-9a5c-ab9b78d5a7bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
