<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg (1)</name>
   <tag></tag>
   <elementGuidId>ece1f52b-1a6d-4703-b53b-618588468984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip Ad'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.videoAdUiSkipIcon > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>996b4d7d-2342-4559-9946-e406b24a9284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>9c83332a-510f-4005-9277-7e7d11734129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>bbdd7311-00eb-4294-b722-1ffdd3e9fd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bee65fc8-e954-406c-b578-6936b99b3a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ad24d97-f89b-412b-b756-44313c745995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>9403af41-c8af-4b5a-8d2c-f8f8473e7abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>1cf2c0b3-1f31-4ca5-aac6-81e84bf41d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveAspectRatio</name>
      <type>Main</type>
      <value>xMidYMid meet</value>
      <webElementGuid>08569a3c-8bd5-4ae0-bf32-fc4e2d2b2fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>98c29637-7729-4ff6-ac68-be7ecf6f7657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ima-sdk-frame&quot;]/body[1]/div[@class=&quot;videoAdUi trueview videoAdUiInstreamUxRefresh videoAdUi-mobile ima-action-ad&quot;]/div[@class=&quot;videoAdUiBottomBar videoAdUiBottomBarCollapsed&quot;]/div[@class=&quot;videoAdUiSkipWidgetV2 noTextSkipButton raisedSkipButton&quot;]/div[@class=&quot;videoAdUiSkipContainer html5-stop-propagation&quot;]/button[@class=&quot;videoAdUiSkipButton videoAdUiAction videoAdUiRedesignedSkipButton&quot;]/div[@class=&quot;videoAdUiSkipIcon&quot;]/svg[1]</value>
      <webElementGuid>488d0aea-0aa6-4f31-9d7a-d8ac9471c51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Temp Mail - Disposable Temporary and F_746997/iframe_concat(id(, , goog_1033885711, , ))_goog_1033885711</value>
      <webElementGuid>892cbd00-3081-4645-ae6f-27c5e74bd439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip Ad'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>1a59703a-ed55-45ea-a5e0-53e4e1f50d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Free'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>8aa6afe7-87f9-41f8-b490-728925eb198c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Free'])[2]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>ed70bbc9-b8be-47f8-bedf-d8fb2bb942d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adobe Acrobat'])[2]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>1443c31b-831b-4c56-a606-7dd986a59ecf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
