<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Terms_iNstf</name>
   <tag></tag>
   <elementGuidId>f19f76a8-05dd-4a18-8314-0916cbd8839a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.iNstf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ed52f0a-f591-4537-b962-52f61bb7a46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iNstf</value>
      <webElementGuid>8e8ba9c2-9c8a-4e44-9aa8-89717181d22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6e459183-65a7-43a9-bc0c-0b10f60f2cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;eC9N2e&quot;]/body[@class=&quot;nyoS7c UzCXuf EIlDfe&quot;]/div[@class=&quot;lJXwje S81Pef TFhTPc LZgQXe&quot;]/div[@class=&quot;iNstf&quot;]</value>
      <webElementGuid>d187c949-54e3-4291-a092-e2d3c7c029f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>fe8a6d5d-c84e-426f-8134-c209a3678675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
