<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_loginEmail AddressEnter PasswordPasswor_6c0a49 - Copy</name>
   <tag></tag>
   <elementGuidId>83a331d5-3f85-4500-8aca-24709b1214a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.login_step1__wZL6p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/form/div/div[3]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e4141d16-ef9f-4fc6-bde3-be81819f2d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_step1__wZL6p</value>
      <webElementGuid>89087f6b-a40c-4e60-80e9-3284ca4465c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>loginEmail AddressEnter PasswordPassword must be at least 8 characters long!Password must contain at least one uppercase letter, one lowercase letter, and one number!OR</value>
      <webElementGuid>82d7261b-08e6-4b97-a354-45a8ccb99fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/form[@class=&quot;ant-form ant-form-horizontal&quot;]/div[@class=&quot;login_register__9PVhU&quot;]/div[@class=&quot;login_wrapper__GYPsU&quot;]/div[@class=&quot;login_modal__lNFbn&quot;]/div[@class=&quot;login_main_wrapper__6oBhw&quot;]/div[@class=&quot;login_step1__wZL6p&quot;]</value>
      <webElementGuid>81aec9a0-15b1-4d8e-a408-4cda956bcac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/form/div/div[3]/div/div/div</value>
      <webElementGuid>13d2034e-aef8-4af6-a5d5-fbf2b818cf81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::div[5]</value>
      <webElementGuid>1161cc94-e853-402e-b464-c73bd716c376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[5]</value>
      <webElementGuid>8dfdcf4b-6984-45b3-81cc-3da549192c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>7d947bab-f7d1-4338-a486-b2927a6c35d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'loginEmail AddressEnter PasswordPassword must be at least 8 characters long!Password must contain at least one uppercase letter, one lowercase letter, and one number!OR' or . = 'loginEmail AddressEnter PasswordPassword must be at least 8 characters long!Password must contain at least one uppercase letter, one lowercase letter, and one number!OR')]</value>
      <webElementGuid>01acc83c-1bfa-4f0c-8ea8-f589b7be72a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
