<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_1</name>
   <tag></tag>
   <elementGuidId>389ae390-d707-4152-b35c-a1af7e4a2ac3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.column.column-5 > table.heading_block.block-2 > tbody > tr > td.pad > h1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/table[@class=&quot;nl-container&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;row row-2&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;row-content&quot;]/tbody[1]/tr[1]/td[@class=&quot;column column-5&quot;]/table[@class=&quot;heading_block block-2&quot;]/tbody[1]/tr[1]/td[@class=&quot;pad&quot;]/h1[1][count(. | //*[@ref_element = 'Object Repository/Page_View message - Mail.tm/iframe_lukpzwkarenkey.com_iFrameResizer0']) = count(//*[@ref_element = 'Object Repository/Page_View message - Mail.tm/iframe_lukpzwkarenkey.com_iFrameResizer0'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[5]/table/tbody/tr/td/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e466312b-f8b7-4262-9f80-c2ef9d549441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4fac5fb4-7aba-45c2-b52c-36f4f3d03606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[@class=&quot;nl-container&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;row row-2&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;row-content&quot;]/tbody[1]/tr[1]/td[@class=&quot;column column-5&quot;]/table[@class=&quot;heading_block block-2&quot;]/tbody[1]/tr[1]/td[@class=&quot;pad&quot;]/h1[1]</value>
      <webElementGuid>d49377d2-0472-43f2-aa60-0656e3291123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_View message - Mail.tm/iframe_lukpzwkarenkey.com_iFrameResizer0</value>
      <webElementGuid>4ea34ec8-1187-4423-b65b-9dbab9791e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td/h1</value>
      <webElementGuid>03f45872-8447-4b5a-befd-dd5c06aa5c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '1' or . = '1')]</value>
      <webElementGuid>1661cc09-52d2-4233-a48f-eb3de5e180f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
