<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , goog_2077007093, , ))_goog_2077007093</name>
   <tag></tag>
   <elementGuidId>63964c07-038e-429a-8660-66097e009cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='goog_2077007093']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#goog_2077007093</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>11a55ceb-7e1d-44b6-9020-ade030ee1837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://imasdk.googleapis.com/js/core/bridge3.547.0_en.html#goog_2077007093</value>
      <webElementGuid>26283672-f270-4a01-83b5-818c3d0539c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay</value>
      <webElementGuid>4801e598-66bd-497d-a9f8-fc3ff778d136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goog_2077007093</value>
      <webElementGuid>55bd9d55-d8e5-403f-8e70-ce037682d4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>1062b0fd-0093-4b3d-b0a3-d259cdc68a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>225</value>
      <webElementGuid>c8e6ce8d-61fd-4926-a4d6-4f880e545659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goog_2077007093&quot;)</value>
      <webElementGuid>2555c4ac-3621-4c2e-9e2b-b6dc0c387fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_View message - Mail.tm/iframe</value>
      <webElementGuid>f8bad826-8c29-4123-8b70-8b2f116b96eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='goog_2077007093']</value>
      <webElementGuid>1997d724-3dea-4267-926e-6ffd82a2e1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4fd2f8d4-0b63-4f1e-9a66-25ab916d23a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://imasdk.googleapis.com/js/core/bridge3.547.0_en.html#goog_2077007093' and @id = 'goog_2077007093']</value>
      <webElementGuid>01e02abf-6771-43f7-99c4-897034f0baca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
